# Generated by Django 4.2.23 on 2025-08-18 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(help_text='Upload an XLSX or CSV file containing order data.', upload_to='order_imports/', verbose_name='Order Import File')),
                ('agent', models.ForeignKey(blank=True, help_text='The agent to which this order import is assigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_imports', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
